port = 5600
discovery_paths = [
  "/home/filip/.local/bin",
  "/home/filip/.local/share/activitywatch/aw-tauri/modules",
  "/home/filip/aw-modules",
]

[autostart]
enabled = true
minimized = true
modules = ["aw-awatcher"]

[module_args]
"aw-awatcher" = ""
